### ISSUE TITLE
yesod 1.4.17.1

### ISSUE THREAD

**Issue by UrKr** [tazjin/elm-yesod#10]
When I run stack install elm-yesod, I get the following error message: 

```
--  While attempting to add dependency,
    Could not find package Elm in known packages

--  Failure when adding dependencies:
      Elm: needed (>=0.7), not present in build plan (latest applicable is 0.13)
      blaze-markup: needed (==0.5.*), 0.7.0.3 found (latest applicable is 0.5.2.1)
      shakespeare-js: needed (-any), not present in build plan (latest applicable is 1.3.0)
    needed for package: elm-yesod-0.2

--  While attempting to add dependency,
    Could not find package shakespeare-js in known packages

Recommended action: try adding the following to your extra-deps
- Elm-0.13
- shakespeare-js-1.3.0

```

Will this package be getting any updates at this point, to make it compatible? Performing the recommended action still leaves the 'failiure when adding dependencies error'

**Comment by tazjin** [comment]
Hey,
I stopped maintaining this a long time ago, partially because Elm went a slightly different direction than what it looked like at the time.

If you have a need for this you could probably amend the code relatively quickly!

**Comment by UrKr** [comment]
Thanks for the reply! I might look into it.
